# Generated by Django 4.0.3 on 2022-03-08 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record_ID', models.TextField()),
                ('Datensatztyp', models.TextField()),
                ('Kampagnen_ID', models.TextField()),
                ('Kampagne_Kampagnename', models.TextField()),
                ('Kampagnentyp', models.TextField()),
                ('Anzeigenformat', models.TextField()),
                ('Budget', models.TextField()),
                ('Portfolio_ID', models.TextField()),
                ('Kampagnenstartdatum', models.TextField()),
                ('Kampagnenenddatum', models.TextField()),
                ('Budget_Typ', models.TextField()),
                ('URL_der_Landing_Page', models.TextField()),
                ('Landing_Page_ASINs', models.TextField()),
                ('Markenname', models.TextField()),
                ('Markenidentitäts_ID', models.TextField()),
                ('Markenlogo_Asset_ID', models.TextField()),
                ('Headline', models.TextField()),
                ('Anzeigendesign_ASINs', models.TextField()),
                ('Medien_ID', models.TextField()),
                ('Automatisierte_Gebote', models.TextField()),
                ('Gebotsfaktor', models.TextField()),
                ('Anzeigengruppe', models.TextField()),
                ('Max_Gebot', models.TextField()),
                ('Keyword', models.TextField()),
                ('Übereinstimmungstyp', models.TextField()),
                ('Kampagnenstatus', models.TextField()),
                ('Bereitstellungsstatus', models.TextField()),
                ('Status_der_Anzeigengruppe', models.TextField()),
                ('Status', models.TextField()),
                ('Impressions', models.TextField()),
                ('Klicks', models.TextField()),
                ('Ausgaben', models.TextField()),
                ('Bestellungen', models.TextField()),
                ('Einheiten_insgesamt', models.TextField()),
                ('Verkäufe', models.TextField()),
                ('ACOS', models.TextField()),
                ('Platzierungstyp', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dashboard.client')),
            ],
        ),
    ]
