# Generated by Django 4.0.3 on 2022-03-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_databrand_dataproduct_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataProduct',
        ),
    ]
