# Generated by Django 4.0.3 on 2022-03-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_dataproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('P', 'Product'), ('B', 'Brand')], max_length=255)),
                ('Product', models.TextField()),
                ('Entity', models.TextField()),
                ('Operation', models.TextField()),
                ('Campaign_Id', models.TextField()),
                ('Ad_Group_Id', models.TextField()),
                ('Portfolio_Id', models.TextField()),
                ('Ad_Id', models.TextField()),
                ('Keyword_Id', models.TextField()),
                ('Product_Targeting_Id', models.TextField()),
                ('Start_Date', models.TextField()),
                ('End_Date', models.TextField()),
                ('Targeting_Type', models.TextField()),
                ('State', models.TextField()),
                ('Daily_Budget', models.TextField()),
                ('SKU', models.TextField()),
                ('ASIN', models.TextField()),
                ('Bid', models.TextField()),
                ('Keyword_Text', models.TextField()),
                ('Match_Type', models.TextField()),
                ('Bidding_Strategy', models.TextField()),
                ('Placement', models.TextField()),
                ('placementProductPage', models.TextField()),
                ('placementTop', models.TextField()),
                ('Percentage', models.TextField()),
                ('Product_Targeting_Expression', models.TextField()),
                ('Impressions', models.TextField()),
                ('Clicks', models.TextField()),
                ('Click_through_Rate', models.TextField()),
                ('Spend', models.TextField()),
                ('Sales', models.TextField()),
                ('Orders', models.TextField()),
                ('Units', models.TextField()),
                ('Conversion_Rate', models.TextField()),
                ('Acos', models.TextField()),
                ('CPC', models.TextField()),
                ('ROAS', models.TextField()),
                ('Campaign_Name', models.TextField()),
                ('Ad_Group_Name', models.TextField()),
                ('Campaign_State', models.TextField()),
                ('Ad_Group_State', models.TextField()),
                ('Ad_Group_Default_Bid', models.TextField()),
                ('Resolved_Product_Targeting_Expression', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_products', to='dashboard.client')),
            ],
        ),
    ]
