# Generated by Django 4.0.3 on 2022-03-21 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_dataproduct_asin_alter_dataproduct_acos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 4, 46, 55, 16429)),
        ),
    ]
