# Generated by Django 4.0.3 on 2022-03-21 06:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_dataproduct_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproduct',
            name='Acos',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='CPC',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='Click_through_Rate',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='Clicks',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='Conversion_Rate',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='Impressions',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='Orders',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='ROAS',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='Sales',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='Spend',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='Units',
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 6, 9, 50, 953465)),
        ),
        migrations.CreateModel(
            name='AnalyticalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Product'), ('B', 'Brand')], max_length=255)),
                ('Impressions', models.TextField(blank=True)),
                ('Clicks', models.TextField(blank=True)),
                ('Click_through_Rate', models.TextField(blank=True)),
                ('Spend', models.TextField(blank=True)),
                ('Sales', models.TextField(blank=True)),
                ('Orders', models.TextField(blank=True)),
                ('Units', models.TextField(blank=True)),
                ('Conversion_Rate', models.TextField(blank=True)),
                ('Acos', models.TextField(blank=True)),
                ('CPC', models.TextField(blank=True)),
                ('ROAS', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 21, 6, 9, 50, 937274))),
                ('data_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytical_values', to='dashboard.databrand')),
                ('data_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytical_values', to='dashboard.dataproduct')),
            ],
        ),
    ]
