# Generated by Django 4.0.3 on 2022-03-21 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_analyticalvalue_campaign_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataproduct',
            old_name='Ad_Group_State',
            new_name='Ad_Group_Default_Bid_info_only',
        ),
        migrations.RenameField(
            model_name='dataproduct',
            old_name='Campaign_State',
            new_name='Ad_Group_Name_info_only',
        ),
        migrations.RenameField(
            model_name='dataproduct',
            old_name='Resolved_Product_Targeting_Expression',
            new_name='Ad_Group_State_info_only',
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='Campaign_Name_info_only',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='Campaign_State_info_only',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='Resolved_Product_Targeting_Expression_info_only',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticalvalue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 22, 0, 20, 819174)),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 22, 0, 20, 841811)),
        ),
    ]
