# Generated by Django 4.0.3 on 2022-03-21 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_ad_group_state_dataproduct_ad_group_default_bid_info_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalvalue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 22, 1, 15, 534913)),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 22, 1, 15, 551629)),
        ),
    ]
