# Generated by Django 4.0.3 on 2022-03-27 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_analyticalvalue_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalvalue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 9, 24, 18, 404601)),
        ),
        migrations.AlterField(
            model_name='analyticalvalue',
            name='type',
            field=models.CharField(choices=[('P', 'product'), ('B', 'brand')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='End_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='Start_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 9, 24, 18, 421415)),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='type',
            field=models.CharField(choices=[('P', 'product'), ('B', 'brand')], max_length=255),
        ),
    ]
