# Generated by Django 4.0.3 on 2022-04-03 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_analyticalvalue_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databrand',
            name='ACOS',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Anzeigendesign_ASINs',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Anzeigenformat',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Anzeigengruppe',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Ausgaben',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Automatisierte_Gebote',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Bereitstellungsstatus',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Bestellungen',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Budget_Typ',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Datensatztyp',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Einheiten_insgesamt',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Gebotsfaktor',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Headline',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Impressions',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Kampagne_Kampagnename',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Kampagnen_ID',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Kampagnenenddatum',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Kampagnenstartdatum',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Kampagnenstatus',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Kampagnentyp',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Keyword',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Klicks',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Landing_Page_ASINs',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Markenidentitäts_ID',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Markenlogo_Asset_ID',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Markenname',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Max_Gebot',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Medien_ID',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Platzierungstyp',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Portfolio_ID',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Record_ID',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Status_der_Anzeigengruppe',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='URL_der_Landing_Page',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Ubereinstimmungstyp',
        ),
        migrations.RemoveField(
            model_name='databrand',
            name='Verkäufe',
        ),
        migrations.AddField(
            model_name='databrand',
            name='Ad_Format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Ad_Group_Id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Bid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Bid_Multiplier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Bid_Optimization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Brand_Entity_Id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Brand_Logo_Asset_Id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Brand_Logo_URL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Brand_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Budget_Type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Campaign_Id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Campaign_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Creative_ASINs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Creative_Headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Creative_Type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Draft_Campaign_Id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='End_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Entity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Keyword_Id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Keyword_Text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Landing_Page_Asins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Landing_Page_URL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Match_Type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Operation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Portfolio_Id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Product_Targeting_Expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Product_Targeting_Id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Start_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='State',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Video_Media_Ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticalvalue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 15, 7, 36, 133949)),
        ),
        migrations.AlterField(
            model_name='databrand',
            name='Budget',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databrand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 15, 7, 36, 157114)),
        ),
        migrations.AlterField(
            model_name='databrand',
            name='type',
            field=models.CharField(choices=[('P', 'product'), ('B', 'brand')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 15, 7, 36, 155297)),
        ),
    ]
