# Generated by Django 4.0.3 on 2022-04-11 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_databrand_acos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databrand',
            name='Campaign_Serving_Status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Campaign_State',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Landing_Page_Type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrand',
            name='Resolved_Product_Targeting_Expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticalvalue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 17, 7, 10, 337067)),
        ),
        migrations.AlterField(
            model_name='databrand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 17, 7, 10, 387410)),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 17, 7, 10, 385248)),
        ),
    ]
