# Generated by Django 4.0.3 on 2022-04-13 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_databrand_campaign_serving_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalvalue',
            name='Bid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticalvalue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 2, 11, 41, 277011)),
        ),
        migrations.AlterField(
            model_name='databrand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 2, 11, 41, 294494)),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 2, 11, 41, 293199)),
        ),
    ]
